config/routes.rb
Rails.application.routes.draw do
  root "quotes#index"
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :quotes do
    resources :replies, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i[create destroy]
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140,
                                                too_long: '140 characters in post is the maximum allowed.' }
  belongs_to :user, foreign_key: :author_id
  has_many :replies, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /quotes
  def index
    @likes = Like.all
    @quotes = Quote.all.order('created_at DESC').includes(%i[user replies])
    @users = User.order('created_at DESC').includes(%i[followed_users followers replies quotes])
    return unless current_user

    @quote = current_user.quotes.new
    @not_followed = User.all.order('created_at DESC') - current_user.followed_users
    @not_followed.delete(current_user)

    ids = current_user.followed_users.ids
    ids << current_user.id
    @followed_and_user_quotes = @quotes.where(author_id: ids)
  end

  # GET /quotes/1
  def show
    @likes = Like.all
    @users = User.all
    @quotes = Quote.all.order('created_at DESC')
    return unless current_user

    @quote = current_user.quotes.new
    @not_followed = User.all.order('created_at DESC') - current_user.followed_users
    @not_followed.delete(current_user)
    @followed_and_user_quotes = @quotes.where(author_id: current_user.followed_users.pluck(:id))
  end

  # GET /quotes/new
  def new
    @quote = current_user.quotes.build
  end

  # GET /quotes/1/edit
  def edit; end

  # POST /quotes
  def create
    @quote = current_user.quotes.build(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to root_path, notice: 'Quote was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to root_path, notice: 'Quote was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quote
    @quote = Quote.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def quote_params
    params.require(:quote).permit(:content)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def custom_timeline
    friends = current_user.followed_users
    friends_quotes = []
    if friends.empty?
      friends_quotes = current_user.quotes
    else
      friends.each do |friend|
        user_finder = User.find(friend.id)
        friends_quotes = user_finder.quotes + current_user.quotes
      end
    end
    friends
  end

  def edit_delete_own_quote
    return unless current_user?(@quote.user)

    link_to edit_quote_path(@quote), class: 'level-item' do
      raw("  <span class='icon'>
            <i class='fa fa-pencil' aria-hidden='true'></i>
        </span>")
    end

    link_to @quote, method: :delete, data: { confirm: 'Are you sure you want to delete this quote?' },
                    class: 'level-item' do
      raw("  <span class='icon'>
            <i class='fa fa-trash-o' aria-hidden='true'></i>
        </span>")
    end
  end

  def delete_own_quote(quote)
    return unless current_user == quote.user

    link_to quote, method: :delete, data: { confirm: 'Are you sure you want to delete this quote?' },
                   class: 'level-item delet' do
      raw("<span class='icon'>
            <i class='fa fa-trash-o'  aria-hidden='true'></i>
        </span>")
    end
  end
end

app/views/quotes/_form.html.erb
<%=  simple_form_for(@quote) do |f| %>
<%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :content, label: "Inspire someone with a quote", input_html: { class: "input"}, wrapper: false, 
      label_html: {class: "label"}, placeholder: "Write a Quote...", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info create-quote" %>
<% end %>

app/views/quotes/_quote.html.erb
 <% @followed_and_user_quotes.each do |quote| %>
      <div class="box no-border">
      <article class="media">
          <div class="media-left">
              <figure class="image is-64x64">
                  <%= gravatar_image_tag(quote.user.email, size: 64, alt: quote.user.fullname) %>

              </figure>
          </div>

          <div class="media-content">
              <div class="content quote-org mb-0">
                  <div class="fullname">
                      <%= link_to quote.user.fullname, user_path(quote.user), class: 'fullname' %><br>
                      <small>@<%= link_to quote.user.username, user_path(quote.user), class: 'post-author' %></small><br />

                      <div class="is-flex is-justify-content-space-between like">
                          <p><%= quote.content %> </p>

                      </div>
                      <div class="likke mt-2 pt-1"><%= quote.likes.count %>
                          <%= like_or_dislike_btn(quote) %></div>

                  </div>
                  <div class="quote-icon is-flex">
                      <div class="mt-3">
                        <%= link_to edit_quote_path(quote), class: 'level-item edit' do %>
                          <span class="icon">
                              <i class="fa fa-pencil" aria-hidden="true"></i>
                          </span>
                        <% end %>
                        <%= delete_own_quote(quote) %>
                      </div>

                  </div>
              </div>
              <nav class="block">

                  <div class='post-comments-section'>
                      <div class="pl-2">
                          <%= render partial: 'replies/reply', collection: quote.replies %>

                          <%= form_for(quote.replies.new, url: quote_replies_path(quote)) do |form| %>
                          <div class="reply-input"><%= form.text_field :content, label: "Quote about it", input_html: { class: "input"},
                                                  wrapper: false, label_html: {class: "label"}, placeholder: "Reply this quote.",
                                                  autofocus: true %></div>
                          <%= form.button :submit, class: "button is-info mt-1" %>
                          <% end %>
                      </div>
                  </div>

              </nav>
          </div>

      </article>
        </div>
      <% end %> 

app/views/quotes/_who_to_follow.html.erb
<div class="wtf-panel px-3 py-5">
    <nav class="">
        <p class="wtf-heading pb-4 mb-4">WHO TO FOLLOW</p>

        <% @not_followed.each do |user| %>
        <article class="wtf-item">
            <div class="justify column">
                <div class="is-flex">
                    <figure class="image is-32x32 thumb">
                        <%= gravatar_image_tag(user.email, size: 64, alt: user.fullname) %>
                    </figure>
                    <div class="ml-2">
                        <p class="fullname"> <%= link_to user.fullname, user_path(user) %><br>
                        </p>
                    </div>
                </div>
            </div>

        </article>
        <%end %>
    </nav>
</div>

app/views/quotes/edit.html.erb
<div class="py-2">
     <article class="media box">
         <figure class="media-left">
             <p class="image is-64x64">
                 <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.fullname) %>

             </p>
         </figure>
         <div class="media-content">
             <%= render 'form' %>
         </div>
     </article>
     <%= link_to 'Show', root_path %> |
     <%= link_to 'Back', quotes_path %>

 </div>

app/views/quotes/index.html.erb
<div class="is-flex h-10">
 
 <div class="column px-5">

    <div class="py-2">
        <article class="media box">
            <figure class="media-left">
                <p class="image is-64x64">
                    <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.fullname) %>

                </p>
            </figure>
            <div class="media-content">
                <%= render 'form' %>
            </div>
        </article>
    </div>
    
<%= render 'quotes/quote' %>

</div>
  
     
 <%= render 'who_to_follow' %> 
    </div>

app/views/quotes/new.html.erb
<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="py-2">
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <%= gravatar_image_tag(@quote.user.email, size: 64, alt: @quote.user.fullname) %>
            </p>
        </figure>
        <div class="content quote-org justify">
            <div>
                <%= link_to @quote.user.fullname, user_path(@quote.user), class: 'post-author' %><br>
                <small>@<%= link_to @quote.user.username, user_path(@quote.user), class: 'post-author' %></small><br />

                <p><%= @quote.content %></p>
            </div>
            <div class="quote-icon">
               
                <%= edit_delete_own_quote %>                               
            </div>
        </div>
</div>

<div class="media-content">

    <nav class="block">
        <div class='post-comments-section pl-4'>
                <%= render partial: 'replies/reply', collection: @quote.replies %>

                <%= form_for(@quote.replies.new, url: quote_replies_path(@quote)) do |form| %>
                <div class="reply-input"><%= form.text_field :content, label: "Quote about it", input_html: { class: "input"},
                                                  wrapper: false, label_html: {class: "label"}, placeholder: "Reply this quote.",
                                                  autofocus: true %></div>
                <%= form.button :submit, class: "button is-info my-2" %>
                <% end %>
               <%= link_to 'Show', @quote %> |
          <%= link_to 'Back', quotes_path %> </div>

    </nav>
</div>

</article>

</div>