config/routes.rb
Rails.application.routes.draw do
  root "quotes#index"
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :quotes do
    resources :replies, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_.]*$/, multiline: true

  has_many :quotes, dependent: :destroy, foreign_key: :author_id
  has_many :replies, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: 'followed_id',
                                   class_name: 'Relationship',
                                   dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def following?(other_user)
    relationships.find_by_followed_id(other_user)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  attr_writer :login

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.includes(%i[replies quotes likes followed_users followers])
    @followed_and_user = current_user.followed_users
  end

  def show
    @user = User.find(params[:id])
    @quotes = @user.quotes.order('created_at DESC')
  end
end

app/helpers/user_helper.rb
module UserHelper
  def current_user?(user)
    current_user == user
  end

  def not_followed(user)
    User.where.not(follower_id: user)
  end

  def follow_unfollow
    return if current_user?(@user)

    if current_user.following?(@user)
      render 'unfollow'
    else
      render 'follow'
    end
  end

  def user_feed
    if current_user.following?(@user) || current_user == @user
      if @user.quotes.empty?
        raw("<p class='box'>This user does not have posts.</p>")
      else
        render 'feed'
      end
    else
      raw("<p class='box'>Follow this user to see his/her posts.</p>")
    end
  end
end

app/views/users/_feed.html.erb
<div class="box no-border">

      <% @user.quotes.each do |quote| %>
     
      <article class="media">
          <div class="media-left">
              <figure class="image is-64x64">
                  <%= gravatar_image_tag(quote.user.email, size: 64, alt: quote.user.fullname) %>

              </figure>
          </div>

          <div class="media-content">
              <div class="content quote-org mb-0">
                  <div>
                      <%= link_to quote.user.fullname, user_path(quote.user), class: 'post-author' %><br>
                      <small>@<%= link_to quote.user.username, user_path(quote.user), class: 'post-author' %></small><br />

                      <div class="is-flex is-justify-content-space-between like">
                          <p><%= quote.content %> </p>

                      </div>
                      <div class="likke mt-2 pt-1"><%= quote.likes.count %>
                          <%= like_or_dislike_btn(quote) %></div>

                  </div>
                  <div class="tweet-icon is-flex">
                      <div class="mt-3">
                         
                          <% if current_user==quote.user %>

                          <%= link_to edit_quote_path(quote), class: 'level-item edit' do %>
                          <span class="icon">
                              <i class="fa fa-pencil" aria-hidden="true"></i>
                          </span>
                          <% end %>

                          <%= link_to quote, method: :delete, data: {confirm: "Are you sure you want to delete this tweet?"}, class: 'level-item delet' do %>
                          <span class="icon">
                              <i class="fa fa-trash-o"  aria-hidden="true"></i>
                          </span>
                          <% end %>
                          <% end %>
                      </div>

                  </div>
              </div>
              <nav class="block">

                  <div class='post-comments-section'>
                      <div class="pl-2">
                          <%= render partial: 'replies/reply', collection: quote.replies %>

                          <%= form_for(quote.replies.new, url: quote_replies_path(quote)) do |form| %>
                          <div class="reply-input"><%= form.text_field :content, label: "Quote about it", input_html: { class: "input"},
                                                  wrapper: false, label_html: {class: "label"}, placeholder: "Reply this quote.",
                                                  autofocus: true %></div>
                          <%= form.button :submit, class: "button is-info mt-1" %>
                          <% end %>
                      </div>
                  </div>
              </nav>
          </div>

      </article>
      <% end %> 
  </div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-info ", id: "follow" %>
<% end %>

app/views/users/_profile.html.erb
<div class="wtf-panel py-5">
    <nav class="">
        <article class=" py-2 wtf">
            <div class="media-content ">
                    <figure class=" thumb">
                    <%= gravatar_image_tag(@user.email, size: 64, alt: @user.fullname) %>
                </figure>
                <p><%= @user.fullname  %></p>
                <p><small>@<%= @user.username  %></small></p>
                <%= follow_unfollow %>
            </div>

            <div class="wtf-f media-content mt-2">
                <div class="stat">
                    <p class="has-text-centered	 "><%= @user.quotes.count  %></p>
                    <p class="heading">Quotes</p>
                </div>
                <div class="stat">
                 <p class=" has-text-centered	"><%= @user.followed_users.count  %></p>
                    <p class="heading">Following</p>
                   
                </div>
                <div class="stat">
                    <p class="has-text-centered	"><%= @user.followers.count  %></p>
                    <p class="heading">Followers</p>
                </div>
            </div>

            <div class="followed mt-2">
                Followed by:<br>
                <% @user.followers.each do |user| %>
                <br>
                 <div class="is-flex">
                <figure class="image is-32x32 thumb">
                    <%= gravatar_image_tag(user.email, size: 64, alt: user.fullname) %>
                </figure>
                <div class="ml-2 lef">
                    <p class="fullname"> <%= link_to user.fullname, user_path(user) %><br>
                    </p>
                    <p class="greyy">@<%= link_to user.username, user_path(user) %><br>
                    </p>
                </div>
                </div>
            </div>
                <%end %>
            </div>
        </article>
    </nav>
</div>

app/views/users/_side_panel.html.erb
<div class="column px-0">
    <nav class="panel pl-3">
       
        <div class="prof-pic">
         <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.fullname) %>
        
        <%= link_to 'PROFILE', user_path(current_user), class: "navbar-item" %>   </div>
        <nav class="level is-mobile">

  <div class="panel-block has-text-centered">
    <div>
      <p class="heading">Following</p>
      <p class="panel-block"><%= current_user.followed_users.count  %></p>
    </div>
  </div>
  <div class="panel-block has-text-centered">
    <div>
      <p class="heading">Followers</p>
      <p class="panel-block"><%= current_user.followers.count  %></p>
    </div>
  </div>

</nav>
<div class="side-links">
        <a href="#" ><%= link_to 'HOME', root_path, class: "navbar-item" %></a>
        <a href="#" ><%= link_to 'CONNECT', users_path, class: "navbar-item" %></a>

        </div>
    </nav>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large ", id: "unfollow" %>
<% end %>

app/views/users/index.html.erb
<section class="users-section">

</section>
<div class="box">

    <% @users.each do |user| %>

    <article class="media">
        <div class="media-left">
            <figure class="image is-64x64">
                <%= gravatar_image_tag(user.username, size: 64, alt: user.username) %>
            </figure>
        </div>

        <div class="media-content">
            <div class="content">

                <%= link_to user.fullname, user_path(user), class: 'post-author' %><br>
                <small><%= link_to user.username, user_path(user), class: 'post-author' %></small><br />

            </div>

        </div>

    </article>

    <% end %>
</div>

app/views/users/show.html.erb
<div class="columns">

    <div class="w-1 pl-3">

        <section class="users-section">
            <div class="media-left mr-0 pt-3">
                <figure class="image profile-pic">
                    <%= gravatar_image_tag(@user.email, size: 64, alt: @user.fullname) %>
                </figure>
            </div>
            <article class="timeline">
                <ul class="posts">
                    <h3 class="box title mb-0 no-border">All Quotes</h3>
                    <ul class="posts">
                        <%= user_feed %>
                    </ul>
            </article>
        </section>
    </div>
    <%= render 'profile' %>

</div>